name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-dev --no-progress

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        env:
          APP_ENV: prod
          APP_DEBUG: 0
        run: |
          npm ci
          npm run build
          npm pack

      - name: Get Node.js cache directory
        id: node-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.node-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/atd-cf-xml-importer.zip"
          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}